title: "Nils Blossey"
remote_theme: orderedlist/minimal
plugins:
  - jekyll-remote-theme
description: >
  Doctoral Researcher in Political Science, University of Cologne <br>
  <a href="mailto:blossey@wiso.uni-koeln.de">Email</a><br>
  <a href="/cv.pdf">Curriculum Vitae</a><br>
  <a href="https://scholar.google.de/citations?user=2_n5Lp4AAAAJ&hl=de&oi=ao">Google Scholar</a><br>
  <a href="https://bsky.app/profile/nilsblossey.bsky.social">Bluesky</a><br>
  <a href="https://x.com/blossey_nils">X</a>
