title: "Nils Blossey"
theme: jekyll-theme-minimal
description: >
  Doctoral Researcher in Political Science, University of Cologne <br>
  <a href="mailto:blossey@wiso.uni-koeln.de">Email</a> 路 
  <a href="/cv.pdf">Curriculum Vitae</a> 路 
  <a href="https://scholar.google.de/citations?user=2_n5Lp4AAAAJ&hl=de&oi=ao">Google Scholar</a> 路 
  <a href="https://bsky.app/profile/nilsblossey.bsky.social">Bluesky</a> 路 
  <a href="https://x.com/blossey_nils">X</a>
