title: "Nils Blossey"
theme: jekyll-theme-minimal
description: |
  Doctoral Researcher in Political Science, University of Cologne  
  [Email](mailto:blossey@wiso.uni-koeln.de) 路 [Curriculum Vitae](/cv.pdf) 路  
  [Google Scholar](https://scholar.google.de/citations?user=2_n5Lp4AAAAJ&hl=de&oi=ao) 路  
  [Bluesky](https://bsky.app/profile/nilsblossey.bsky.social) 路  
  [X](https://x.com/blossey_nils)
